---
# tasks file for users
    - name: Add user skill on server
      ansible.builtin.user:
        name: skill
        shell: /bin/bash
    - name: Create ssh dir on skill
      ansible.builtin.file:
        path: ~skill/.ssh
        state: directory
        owner: skill
        group: skill
        mode: 0700
    - name: Upload SSH Key
      ansible.builtin.copy:
        src:  key
        dest: ~skill/.ssh/id_rsa.pub
        owner: skill
        group: skill
        mode: 0700
