---
# tasks file for http
- name: Install nginx+php
  ansible.builtin.yum:
    name: 
      - nginx

- name: Enable nginx and php-fpm systemd
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    masked: no

- name: Copy nginx.conf
  ansible.builtin.copy:
    src:  nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx 
    state: started

