---
- name: Install nginx+php
  ansible.builtin.yum:
    name: 
      - nginx
      - php
      - php-fpm 

- name: Enable nginx and php-fpm systemd
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    masked: no

- name: Enable nginx and php-fpm systemd
  ansible.builtin.systemd:
    name: php-fpm 
    enabled: true
    masked: no

- name: Create root Dir for nginx-php
  ansible.builtin.file:
     path:  /opt/nginx/php
     state: directory
     mode: '0755'

- name: Copy index.php
  ansible.builtin.copy:
    src:  index.php
    dest: /opt/nginx/php/index.php
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy nginx.conf
  ansible.builtin.copy:
    src:  nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
      - Restart nginx

- name: Start php-fpm 
  ansible.builtin.systemd:
    name: php-fpm
    state: started

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx 
    state: started
